name: Update flake inputs
on:
  schedule:
    # Update every Sunday and Wednesday
    - cron: "51 3 * * 0,3"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
        persist-credentials: false
        fetch-depth: 0
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210415_76980a1/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Update & commit lockfile
        run: |
          git config --local user.email "flakebot@users.noreply.github.com"
          git config --local user.name "flakebot"
          nix flake update --commit-lock-file
      - name: Check home-manager script
        run: nix run . -- help
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          # Use a custom token so we can trigger other workflows upon push to master
          github_token: ${{ secrets.FLAKEBOT_TOKEN }}
          branch: master
          force: true
